AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Provision the AWS Lambda function

Parameters:

  env:
    Type: String
    Default: dev
    Description: Environment Name

Resources:
  MamipFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: !Sub mamip-${env}
      Description: MAMIP - Monitor AWS Managed IAM Policies Changes
      Handler: fireup.lambda_handler
      Runtime: python3.7
      CodeUri: ./build
      MemorySize: 128
      Timeout: 30
      Layers:
        - arn:aws:lambda:eu-west-1:567589703415:layer:boto3-layer:8
      Policies:
        - AWSLambdaExecute # Managed Policy
        - Version: '2012-10-17' # Policy Document
          Statement:
            - Effect: Allow
              Action:
              - ec2:DescribeInstances
              - ec2:RequestSpotInstances
              - ec2:RunInstances
              - iam:PassRole
              Resource: '*'
      Events:
        Timer:
          Type: Schedule
          Properties:
            Schedule: rate(1 day)
      Tags:
        Project: mamip