on:
  push:
    branches:
    - dev

name: Policy Validation

jobs:
  build:
    name: AWS Access Analyzer - Policy Validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: AWS IAM Assume Role
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.REGION }}
          role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}
          role-duration-seconds: 1200
          role-session-name: GH-Actions-${{ env.project }}
      - name: Who Am I?
        run: aws sts get-caller-identity

      - name: Python version
        run: pyton3 --version

      # - name: Install Python3
      #   run: sudo apt-get install python3


      - name: Install boto3
        run: python3 -m pip install -r /automation/requirements.txt
