on:
  push:
    branches:
    - master

name: AAA - Policy Validation

jobs:
  build:
    name: AWS Access Analyzer - Policy Validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
      - name: AWS IAM Assume Role
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.REGION }}
          role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}
          role-duration-seconds: 1200
          role-session-name: GH-Actions-${{ env.project }}
      
      - name: Who Am I?
        run: aws sts get-caller-identity
      
      - name: Python version
        run: python3 --version
      
      - name: pwd
        run: |
          pwd
          ls -l
      
      - name: Install python requirements
        run: python3 -m pip install -r ./automation/requirements.txt

      - name: AWS Access Analyzer - Policy Validation
        run: python3 ./automation/validate-batch.py

      - name: Commit findings
        run: |
          git config --local user.email "mamip@noreply"
          git config --local user.name "mamip-github-actions[bot]"
          git add ./findings
          git commit -m "Add AWS Access Analyzer findings"

      - name: Push findings
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
