on:
  push:
    tags:
      - '202*'

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # - id: files
      #   uses: jitterbit/get-changed-files@v1

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Update detected on ${{ github.ref }}
          # Added: ${{ steps.files.outputs.added }}
          # Modified: ${{ steps.files.outputs.modified }}
          # Removed: ${{ steps.files.outputs.removed }}
          draft: false
          prerelease: false

      - name: Get changed files
        id: getfile
        run: |
            export DIFF=$( git diff --name-only origin/master ${{ github.sha }} )
            echo "Diff between origin/master and ${{ github.sha }} "
            export DIFF2=$( git diff --name-only ${{ github.event.before }} ${{ github.sha }} )
            echo "Diff2 between ${{ github.event.before }} and ${{ github.sha }} "
            echo "--DIFF1:"
            echo "$DIFF"
            echo "--DIFF2:"
            echo "$DIFF2"