on:
  push:
    tags:
      - '202*'

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - id: file_changes
        uses: trilom/file-changes-action@v1.2.3
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Update detected on ${{ github.ref }}
            Files changed: '${{ steps.file_changes.outputs.files}}
            Modified: ${{ steps.file_changes.outputs.files_modified}}
            Added: ${{ steps.file_changes.outputs.files_added}}
            Removed: ${{ steps.file_changes.outputs.files_removed}}
          draft: false
          prerelease: false