on:
  push:
    tags:
      - '202*'

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get changed files
        id: getfile
        run: |
            export PREVIOUS=$( git describe --abbrev=0 --tags `git rev-list --tags --skip=1 --max-count=1` )
            export DIFF=$( git diff --name-only ${{ github.ref }} $PREVIOUS )
            echo "PREVIOUS: $PREVIOUS"
            echo "DIFF: $DIFF"

            filechange=$DIFF
            filechange="${filechange//'%'/'%25'}"
            filechange="${filechange//$'\n'/'%0A'}"
            filechange="${filechange//$'\r'/'%0D'}"
            echo "::set-output name=filechange_clean::$filechange"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            File changed: 
            ${{ steps.getfile.outputs.filechange_clean }}
          draft: false
          prerelease: false